Adding files for Assignment 1. Updated requirements.
colinanderson10/ColinPythonProject pull request #1
Opened 2020-09-05 08:56 UTC by colinanderson10

2020-09-05 22:23 UTC, my-cabbages requested changes

2020-09-05 22:23 UTC, i-baumann commented on requirements.in
> +pandas
Add `plotly` and `sklearn` so that `pip-compile` will pick them up

2020-09-05 22:23 UTC, i-baumann commented on Assignment1/Assignment1.py
> +    X = normalizer.transform(X_orig)
This transform is already happening inside the pipeline.

2020-09-05 22:23 UTC, i-baumann commented on Assignment1/Assignment1.py
> +    random_forest.fit(X, y)
Remove, this fit is happening at the end of end of the pipeline.

2020-09-05 22:23 UTC, i-baumann commented on Assignment1/Assignment1.py
> +    neigh.fit(X, y)
Remove, this fit is happening at the end of the pipeline.

2020-09-05 22:23 UTC, i-baumann commented on Assignment1/Assignment1.py
> +    print("\nRandom Forest Score:", pipeline.score(X, y))
```suggestion
    print("\nRandom Forest Probability:\n", pipeline.predict_proba(X_orig))
    print("\nRandom Forest Score:", pipeline.score(X_orig, y))
```
Since the transform of `X_orig` is happening in the pipeline you want to predict probabilities/score off the original non-transformed data (or test data). I don't think it makes any difference in this particular setting, but the transformation outside of the pipeline is redundant if it's happening in the pipeline.

2020-09-05 22:23 UTC, i-baumann commented on Assignment1/Assignment1.py
> +    pipeline = Pipeline(
Give the pipelines different names.

2020-09-05 22:23 UTC, i-baumann commented on Assignment1/Assignment1.py
> +    print("\nNearest Neighbor Score:", pipeline.score(X, y))
```suggestion
    print("\nNearest Neighbor Probability:\n", pipeline.predict_proba(X_orig))
    print("\nNearest Neighbor Score:", pipeline.score(X_orig, y))
```
Same comment as before.

2020-09-05 22:23 UTC, i-baumann commented on Assignment1/Assignment1.py
> +    print("\nDescriptive Statistics through Pandas\n", iris.describe())
Do you think we should ask Julien if he's cool with us using `.describe` for this? I also did this and prefer it way more than printing individual summary stats with numpy or recursively building a janky table of stats, just remembered he said to use numpy and am wondering what you think.

2020-09-05 22:23 UTC, my-cabbages commented on Assignment1/Assignment1.py
> +    # Make Plots
I dunno why `plotly` is so fickle, but try forcing it to display all plots a particular way (like in browser). In both pycharm and vscode the plots run but don't prompt display.

2020-09-06 21:53 UTC, colinanderson10 commented
Made the suggested changes. Thanks for the very helpful comments!

2020-09-09 05:07 UTC, my-cabbages approved these changes

2020-09-12 22:28 UTC, dafrenchyman approved these changes
Everything was great. I liked how the code was organized. One thing I would recommend is look up “snake case” (https://en.wikipedia.org/wiki/Snake_case). In python the convention is to use that over camelCase. You were mixing different styles up in here. Great job!

2020-09-12 22:28 UTC, merged